core/src/Root.ts
core/src/State/FocusedElement.ts
core/src/Types.ts
demo/src/demo.tsx

* Changes mover API to object instead of enum
* Change the typing to use enum instead of interface+const
* Add cyclic navigation check to `FocusedElement` API

Support cyclic mover navigation

---

core/src/AbilityHelpers.ts
core/src/index.ts
demo/src/demo.tsx

* Adds internal window instance of AH on creation
* Added  `abilityHelpersExists` helper method
* Throw error on `createAbilityHelpers` if an AH instance already exists on the window

Encourage single AH instance on window

---

core/src/State/FocusedElement.ts

Home/End keys will now navigate to the appropriate first/last elements
in a mover group

Support Home/End keys for Mover

---

core/src/Focusable.ts
core/src/Types.ts
demo/src/demo.tsx

Adds a method `findAll` which will return all the elements in a context
of a root element with a provided custom check.
The default `isFocusable` can be skipped explicitly and the
documentation warns against doing so.

Add findAll to Focusable API

---

core/src/State/FocusedElement.ts
examples/src/Mover.stories.tsx

We consider a mover to be a single tab stop, therefore when focus is inside the mover:
1. TAB - should move to the next focusable element outside the mover
2. SHIFT+TAB - should mover the previous focusable element outside the mover
`1.` is already handled by default since walking the tree will always lead to the boundary of the most nested mover
In order to handle `2.` the `FocusedElementState` needs to traverse up the tree to until there is no more mover to determine what is the root mover element.

Handle shift+tab nested movers

---

core/src/Focusable.ts
core/src/Types.ts
examples/src/Focusable.stories.tsx

According to [WAI](https://www.w3.org/TR/wai-aria-practices/#kbd_disabled_controls) spec some `aria-disabled` elements should still be
focusable
This PR adds an `ignoreAriaDisabled` option for focusable so that
Tabster's `isAccessible` check allways passes if set

Focusable can optioanlly ignore aria-disabled

---

package.json

After #18 thanks to @layershifter, there is no more need for poor man automation.
Keeps the pre-push as empty, so that `npm run bootstrap` can clean up existing pre-push hooks

Removes pre-push hooks

---

.github/workflows/github-pages.yml
examples/package.json

A follow up for #21.
Removes `build:prod` in favor of having only `build` as `build-storybook` already creates a production build. Also added `--quiet` option to reduce noise from Webpack Progress Plugin on CI.
Storybook will be deployed into `/storybook` directory on Github pages.

chore: update Storybook deployment to Github pages

---

core/src/Root.ts
core/src/State/FocusedElement.ts
core/src/Types.ts
examples/src/Groupper.stories.tsx
examples/src/Mover.stories.tsx

This PR adds RTL checking for `getTabsterContext` through an extra
option, that checks all ancestors in the dom tree for the `dir`
attribute.
Also uses this new RTL flag to flip arrow keys (left/right) for groupper
and mover use cases.
Resolves #5

RTL awareness for tabster context and arrow keys

---

core/src/Tabster.ts

Simplifies the typing by removing overloads and making both args
optional

Cleanup typing for `getTabsterAttribute`

---

core/package.json

This PR adds `"sideEffects": false` to indicate for bundlers that this package is tree shakable, otherwise we will get bailouts in Webpack:
```
[8] ./src/main.js + 149 modules 255 KiB {0} [built]
ModuleConcatenation bailout: Cannot concat with ./node_modules/tslib/tslib.es6.js because of ./node_modules/tabster/dist/tabster.esm.js
```
https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

chore: add "sideEffects": false to enable tree shaking

---

core/src/State/FocusedElement.ts
core/src/Tabster.ts

Runs Tabster's `keydown` listener for a focused element before the rest
of the window.
Ensures that `Tabster` behaviour runs before user behaviour
i.e.: Tabster drags you into a pit of success and it's up to you to
climb out

FocusedElement: capture keydown listener

---

core/src/Deloser.ts
core/src/Focusable.ts
core/src/Modalizer.ts
core/src/Root.ts
core/src/State/FocusedElement.ts
core/src/Types.ts
demo/src/demo.tsx
examples/src/Groupper.stories.tsx
examples/src/Modalizer.stories.tsx

Removes the concept of `accessible` for `Modalizer`
`Modalizer` will set `aria-hidden` on all non-Modalizer content on the document when active, and restore `aria-hidden` when no longer active.
Should result in most `Modalizer` references no longer needed for focusing/finding

Remove modalizer accessibility and set aria-hidden in tree instead

---

core/src/Modalizer.ts
examples/src/Modalizer.stories.tsx

Currently the mutation listener for `Modalizer` only disposes inactive
modalizers. This is a problem for 'stacks' of `Modalizers` (i.e. when
one modalizer opens another one)
When all modalizers in a stack are removed from DOM, some may already
inactive so doesn't get cleaned up.
This changes makes sure that any `Modalizer` removed from DOM will be
dsposed from the `ModalizerAPI`

Fix(Modalizer): Dispose inactive modalizers

---

core/src/Root.ts
core/src/Types.ts

Currently `autoRoot` does not have tabster attributes applied to the DOM
element. This results in mutations not being dispatched to the `RootAPI`
because `getTabsterOnElement` is used on the mutation target before the
observer decides to dispatch the mutation event

Fix(autoRoot): auto root should have tabster attr

---

.github/workflows/github-pages.yml
examples/package.json

Since the tabster repo uses `prepare` during the `bootstrap` command to
build projects, make this consistent with the `examples` project

fix(examples): Add prepare phase to examples

---

core/src/Deloser.ts
core/src/Modalizer.ts
core/src/Types.ts
core/src/__tests__/Deloser.test.tsx
core/src/__tests__/Modalizer.test.tsx

Currently `ModalizerAPI.add` and `DeloserAPI.add` do not check if the new instances are already
focused.
This leads to a bugs if as new instance that is added already has focus.
This can be caused by React's virtual DOM rendering which can't
guarantee the order of mutation event and focus event. 
Added `hasFocus` to `Modalizer` and `Deloser` instances to check if the instance has a focused element inside. Call this method from the `add` APIs to see if the instances should be activated after being created.
Also Added tests to prevent regression. Below are examples for bugs that can occur for `Modalizer` and `Deloser`
Here is an example for the Modalizer:
* focus DOM element
* add tabster modalizer attributes to DOM element
* `ModalizerAPI._onFocus` triggers first and can't find a modalizer …

fix(Modalizer+Deloser): Check if already focused

---

core/src/Focusable.ts
core/src/Root.ts
core/src/State/FocusedElement.ts
core/src/Types.ts
core/src/__tests__/Focusable.test.tsx
core/src/__tests__/FocusedElement.test.tsx
core/src/__tests__/Root.test.tsx
core/testing/BroTest.ts

* check for `disabled` attribute instead of `aria-disabled`
* do not handle keydown for `contextEditable = 'true'` areas
* Add a custom `data-tabster-dummy` for dummy inputs in tabster

fix(Core): Various small fixes

---

core/src/Tabster.ts
core/src/Types.ts
core/src/global.d.ts
core/tsdx.config.js
demo/webpack.config.js
examples/.storybook/main.js
test-container/src/global.d.ts
test-container/webpack.config.js

Uses the rollup replace plugin to add the current version to the code
during build. This version is assigned to each tabster instance

feat(version): Embed the version of the package in each tabster instance

---

core/src/CrossOrigin.ts
core/src/State/ObservedElement.ts
core/src/Types.ts
core/src/__tests__/ObservedElement.test.tsx
test-container/src/index.ts

Previously `requestFocus` did not allow focus for programmatically focusable elements even though it is a programmatic focus since it is called in code

fix(requestFocus): Should focus tabindex=-1

---

core/src/State/ObservedElement.ts
core/src/__tests__/ObservedElement.test.tsx

focusable elements (i.e. tabindex -1)
However, the previous PR missed the extra check in `_trigger` which is
called on observed element udpate. This means that when requesting focus
for an element that does not exist and with tabindex -1 will always fail

fix(ObservedElement): allow programmatically focusable on update

---

core/src/Modalizer.ts
core/src/__tests__/Modalizer.test.tsx
core/testing/BroTest.ts

If a user removes a modalizer from the document before restore focus
happens a race condition can occur where focus is lost because there is
no modalizer to restore focus to.
By restoring focus async, we can wait until the user has finished DOM
mutations before attempting to restore focus, and check if an active
modalizer still exists

fix(Modalizer): Restore focus asynchronously

---

.github/workflows/ci.yml
core/jest.config.json
core/src/Groupper.ts
core/src/Modalizer.ts
core/src/Mover.ts
core/src/Root.ts
core/src/State/FocusedElement.ts
core/src/Tabster.ts
core/src/Types.ts
core/src/Utils.ts
core/src/__tests__/Focusable.test.tsx
core/src/__tests__/Root.test.tsx
core/src/__tests__/Uncontrolled.test.tsx
core/src/__tests__/test-utils.ts
core/testing/BroTest.ts
test-container/src/global.d.ts
test-container/src/index.ts
test-container/webpack.config.js

Abstracts the dummy input logic to a `DummyInputManager` class that can be reused.
The `DummyInputManager` automatically adds dummy focus sentinels as first and last child of an element and will be used in:
* Mover
* Groupper
* Modalizer
So that `FocusedElementState` no longer needs to control **every single tab key press under Root**. This makes it easier for users to adopt tabster gradually.
The new dummy input code path can be configured when creating tabster. **The current codepath is still the default**, where each tab key press is controlled
```tsx
createTabster(window, { controlTab: false });
```
Both codepaths can now be tested in the repo:
```
// Inserts dummy inputs and stops controlling tab
UNCONTROLLED=true npm test
// current main codepath
npm test
```

implement code path with dummy inputs

---

core/src/Utils.ts

In older versions of JSOM jsdom/jsdom#639 mutation observer is not fully
supported and will throw on tests.
Wraps the usage of MutationObserver around the `process.env.NODE_ENV`
guard to protect for this scenario

Mutation observer should not be used in test environment

---

core/src/Tabster.ts
core/src/Utils.ts

tsdx does not support any other environments apart from the
`production` and `development` jaredpalmer/tsdx#167
write the `process.env.NODE_ENV` as `process.env.["NODE_ENV"]` so that
tsdx does not auto replace this

fix: keep `process.env.NODE_ENV` check for test environment

---

core/package.json

Currently in `dist` there are imports of `tslib`, but it's not declared as a dependency:
https://cdn.jsdelivr.net/npm/tabster@1.0.6/dist/tabster.esm.js

chore: add tslib to deps of tabster

---

core/testing/BroTest.ts

Recently CI builds have been failing since the tests start faster than
the server does sometimes. Add retries to tests so they can wait for the
container to start up

fix(tests): Add retries to connect to test container

---

CONTRIBUTING.md
package.json
src/Modalizer.ts
src/__tests__/Modalizer.test.tsx

Fixes #77 by only adding the `keydown` tab handler when tabster is not
controlling tab
The current test actually worked in the buggy state 😨 because there were only 2 focusable elements inside the modalizer, so the second tab press would also find the same element and focus it. Added a third focusable element to catch this bug

fix(Modalizer): Only apply keydown listener in uncontrolled mode

---

src/Deloser.ts
src/Groupper.ts
src/Mover.ts
src/MutationEvent.ts
src/Root.ts
src/State/FocusedElement.ts
src/Tabster.ts
src/Uncontrolled.ts
src/Utils.ts

Also ignores unused props lint rule for `validateProps` since it is a
TODO

Fix some easy lint issues

---

.gitignore
.vscode/settings.json
src/CrossOrigin.ts

Static variables cannot be tree shaken terser/terser#724, therefore
transform the trivial arrow function to be an actual function since
`this` is never used.

chore(CrossOrigin): Refactor static variables to be a static function

---

src/Deloser.ts
src/Groupper.ts
src/Modalizer.ts
src/Mover.ts
src/Root.ts

Using static variables breaks tree shaking of entire classes

chore: refactor `create` functions to be functions not variables

---

package.json

All `tabster` releases are unusable because the `postinstall` step is
trying to `cd` into a directory that does not exist in the published
artifact.
Also removes the `build-docs` command from the `build` command until we docs is intergrated into the repo correctly

fix: remove postinstall script to fix package installation

---

package-lock.json
package.json

Fixes #89.
Used version in this repo (1.1.4) already has required packages as dependencies:
https://github.com/microsoft/fluentui/blob/63afcc3438d77ac815a683f79898854922263a27/packages/bundle-size/package.json#L13-L26

chore: remove unused packages

---

.gitignore
package-lock.json
package.json
rollup.config.js
src/Tabster.ts
src/Types.ts
src/Utils.ts
src/index.ts
src/tsconfig.lib.json

Removes `overrideBasic` from exports since it was never used downstream.
Also rollup types into a single `index.d.ts` file with rollup to avoid
leaking internal types to consumers.
The result is that tabster can be built with Typescript 3.9

fix: Support typescript 3.9 and rollup types

---

rollup.config.js
src/CrossOrigin.ts
src/Deloser.ts
src/Groupper.ts
src/Instance.ts
src/Modalizer.ts
src/Mover.ts
src/MutationEvent.ts
src/Outline.ts
src/Root.ts
src/State/FocusedElement.ts
src/State/ObservedElement.ts
src/Tabster.ts
src/Types.ts
src/Utils.ts
src/tsconfig.lib.json
tests/Internal.test.tsx
tests/KeyboardNavigationState.test.tsx
tests/ObservedElement.test.tsx
tests/Root.test.tsx
tests/utils/test-utils.ts

Refactors the types to have a single `Tabster` type and removes the `TabsterInternal` type that was used only internally (but still leaking externally).
None of the APIs marked with `@internal` will be visible to users and their types are stripped at build time. This means that even internally in the code only once `TabsterCore` type is used

Strip internal tabster APIs with `@internal` and have single `TabsterCore` type usage

---

src/CrossOrigin.ts
src/Deloser.ts
src/Focusable.ts
src/Groupper.ts
src/Instance.ts
src/Modalizer.ts
src/Mover.ts
src/Outline.ts
src/Root.ts
src/State/FocusedElement.ts
src/State/KeyboardNavigation.ts
src/State/ObservedElement.ts
src/State/Subscribable.ts
src/Tabster.ts
src/Types.ts

Since we now strip `@internal` types from the final API, `dispose` and other internal public functions won't be visible to end users. We can remove most static functions from APIs

use internal class functions instead of static functions

---

src/Modalizer.ts
src/State/FocusedElement.ts
src/Types.ts
stories/Modalizer/ModalDialog.ts
stories/Modalizer/Modalizer.stories.ts
tests/Modalizer.test.tsx

Implements a new prop for Modalizer `isTrapped` which allows focus to
stay within the Modalizer and never leave the it. The prop is
implemented for both controlled an uncontrolled code paths in Tabster.
Fixes #122

feat: Allow circular focus trap in Modalizer

---

src/index.ts

getCurrentTabster was removed in #136 to promote usage of lightweight
tabster instance. However this is actually a breaking change. Reexport
the utility function.

fix: re-export getCurrentTabster

---

src/Tabster.ts
tests/Tabster.test.tsx
tests/index.html
tests/utils/BroTest.ts

Fixes backwards compat issue of Tabster/TabsterCore instances introduced
with #136

fix: get<API> should accept both Tabster and TabsterCore instance

---

src/Tabster.ts

Follow up of #161. `instanceof` can be dangerous to use because the
result depends on the execution context. Comparing the same classes from
different execution contexts can actually return `false`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_contexts_e.g._frames_or_windows

fix: use predicate to assert tabster type instead of `instanceof`

---

package.json
src/Root.ts
src/State/FocusedElement.ts
src/Types.ts
tests/Mover.test.tsx

Adds a focusable attribute called `ignoreKeydown` to let users bail out of tabster keydown handling. This can be useful when users would like to custom handle `Tab` behaviour inside APIs like the `Mover`

feat: Add `ignoreKeydown` focusable attribute

---

src/Utils.ts

When a `DummyInputManagerCore` is created it attaches itself to a HTML
element. When it is disposed it does not remove itself from the HTML
element.
When a new tabster core is created it will still use the undisposed
`DummyInputManagerCore` and causes a leak where a disposed tabster core
is being used

fix: Dispose `__tabsterDummy` on DummyInputManagerCore

---

src/Utils.ts

Calling the real dummy inputs update positions function only after the scrolling ends.

fix: Avoid updating dummy inputs positions while scrolling to avoid excessive reflows.

---

src/State/FocusedElement.ts
tests/FocusedElement.test.tsx
tests/utils/BroTest.ts

On a native app, where the host does not own the Ctrl + Tab hotkey, Tabster is handling the ctrl+tab hotkey as Tab.
Code Change.
Check whether the event contains CtrlKey before handling the onKeyEvent

Do not handle the FocusedElement onKeyDown when using Ctrl + Tab

---

src/Focusable.ts
src/Groupper.ts
src/Modalizer.ts
src/Mover.ts
src/Root.ts
src/State/FocusedElement.ts
src/Types.ts
src/Utils.ts
tests/DummyInputManager.test.tsx
tests/Groupper.test.tsx
tests/Mover.test.tsx
tests/MoverGroupper.test.tsx
tests/Uncontrolled.test.tsx

This change addresses two issues:
1. Historically, we were adding new features without seeing the whole picture as we see it now. 
2. We weren't fully aware of how TreeWalker actually works when you walk backwards in the DOM.
These two things have lead us into a state when the implementation of finding elements is rather patchy and at this point it is hard to understand and hard to adjust for new corner cases (because whenever something new gets fixed, something old gets broken).
Plus it fixes a bunch of connected bugs (primarily the Shift+Tab ones).

Big find elements refactoring

---

src/Groupper.ts
src/Utils.ts
tests/CrossOrigin.test.tsx
tests/Deloser.test.tsx
tests/DummyInputManager.test.tsx
tests/Focusable.test.tsx
tests/FocusedElement.test.tsx
tests/Groupper.test.tsx
tests/Internal.test.tsx
tests/KeyboardNavigationState.test.tsx
tests/Modalizer.test.tsx
tests/Mover.test.tsx
tests/MoverGroupper.test.tsx
tests/ObservedElement.test.tsx
tests/Root.test.tsx
tests/Uncontrolled.test.tsx
tests/iframeFocus.test.tsx

By default Grouppers in uncontrolled mode put dummy inputs outside of the container, which is bad HTML for elements like `<li>`, `<td>` and `<th>`. So, we handle that case putting dummy inputs inside when those elements are used.

fix(Groupper): Putting dummy inputs inside the groupper container when it is <li>, <td> or <th>.

---

src/CrossOrigin.ts
tests/CrossOrigin.test.tsx

requestFocus() is a programmatic focus call, so it should be able to focus elements with tabindex=-1. ObservedElement.requestFocus() was doing that fine, but the CrossOrigin.observedElement.requestFocus() version wasn't passing the correct flag.

fix(CrossOrigin): requestFocus() from CrossOrigin API should be able to focus programmatically focusable elements.

---

src/Groupper.ts
src/Types.ts
tests/Groupper.test.tsx
tests/MoverGroupper.test.tsx

Generally, when Groupper is Limited or LimitedTrapFocus, the groupper container focusable (so that Enter press on that container moves focus inside the groupper and Esc press moves focus from inside the groupper to the container). We are adding `delegated` property to Groupper which will allow first focusable inside the non-focusable groupper container to behave the same way as the focusable groupper container does.
The example `<div groupper tabindex=0>...</div>` should behave the same way as `<div groupper=delegated><div tabindex=0>...</div></div>` from the Enter/Esc/Tab pressing perspective, the role of focusable container is delegated to the first focusable inside the actual container.

feat(Groupper): Ability to delegate the role of focusable groupper container to first focusble element in groupper.

---

src/EventTarget.ts
src/Root.ts

As a follow up on https://github.com/microsoft/fluentui/issues/24721, to ensure support browser matrix, we'll have to stop using `EventTarget`.
This PR adds a ponyfill method `createEventTarget`, that will create a `div` element and use it as an `EventTarget` in the cases where `EventTarget` class is not available in the `window`.
Fixes https://github.com/microsoft/fluentui/issues/24721

chore: creates EventTarget ponyfill

---

src/Tabster.ts
tests/Tabster.test.tsx
tests/index.html
tests/utils/BroTest.ts

makeNoOp() is broken since we've added core wrappers for createTabster().

fix(Core): Fixing makeNoOp().

---

src/AttributeHelpers.ts
src/Root.ts
src/Tabster.ts
src/index.ts
tests/AttributeHelpers.test.tsx
tests/DummyInputManager.test.tsx
tests/index.html
tests/utils/BroTest.ts

* Fixing autoRoot not functioning properly for Modalizer scenarios.
* Moving Tabster attribute helper functions to a separate file.
* Adding mergeTabsterProps().

Fixing autoRoot and moving Tabster attribute helpers to a separate file.

---

src/Groupper.ts
src/Mover.ts
src/Root.ts
src/State/FocusedElement.ts
src/Types.ts
tests/Mover.test.tsx

Adds a check in the `Mover` keydown handler to check for `ignoreKeydown`. Also refactors the tabster context to return a utility function for `ignoreKeydown` instead of the entire object map.

feat: Mover should support `ignoreKeydown` property

---

docs/docs/mover.md
src/Mover.ts
src/Types.ts
stories/Mover/Mover.ts
tests/Mover.test.tsx

Ability to have default focusable in Mover.

feat(Mover): hasDefault property for Mover that respects Focusable.isDefault flag.

---

src/Mover.ts
tests/Mover.test.tsx
tests/utils/BroTest.ts

Any action perfomed with the CTRL key should be ignored. There is currently no tabster feature that needs to support the CTRL key. Currently key combos like CTRL+HOME are simply doing the same thing as HOME with the addition of the event being swallowed (stopImmediatePropagation) by tabster.
Also updates the testing util so that `pressKey` supports shift and ctrl

fix: Mover should ignore CTRL key

---

src/Modalizer.ts

This error is removed because it does not provide any actionaly information for users to do anything meaningful. The need for a an aria-label will depend a lot on the end user scenario. Tabster should not be responsible for this.

fix: Remove Modalizer warning for aria labels

---

src/Mover.ts
src/Types.ts
src/Utils.ts
tests/Mover.test.tsx
tests/utils/BroTest.ts

Adds a tolerance of 80% to the check `isElementVerticallyVisible`. This means that when an element is cut off by the viewport, as long as the part cut off is 80% visible, the check will return true.
The Mover now supports a `visibilityTolerance` prop so that this tolerance is configurable for each mover. Adds tests to make sure that this tolerance is correctly enforced in scroll containers where elements are partially visible.
This is needed since browser scrolling is not precise enough to have 100% of an element visible all the time. Previously the tolerance was essentially 1px, which is too small.

feat: implement `visibilityTolerance` prop to Mover

---

src/Types.ts
tests/Mover.test.tsx

The library in fact supports this configuration, but the FocusableProps.ignoreKeydown doesn't include it for some reason.
This is needed for my POC of keyboard navigation in the table and interacting with an intractable element:
https://github.com/microsoft/fluentui/pull/26873/files#diff-91a26c39f89f4f6f6ce48e2d580e0c68d2b10706c96f851e5a070a65f0871fe7R47

fix: Add ArrowLeft and ArrowRight to ignoreKeydown type

---

src/Mover.ts
tests/MoverGroupper.test.tsx

Fixing a case when Mover's arrow keys handler was moving focus inside Groupper in Mover/Active Groupper/Inactive Groupper scenario.

fix(Mover): Fixing a corner case in Mover/Groupper/Groupper scenario.

---

src/Mover.ts
tests/Mover.test.tsx

`trackState` and `visibilityAware` were buggy sometimes handling elements that were never visible.

fix(Mover): Fixing trackState when it wasn't firing events for the elements that never were visible before.

---

src/Root.ts
tests/MoverGroupper.test.tsx

When Mover and Groupper are set on the same element, they should be prioritized properly:
If the context element equals to the element which has both Mover and Groupper, Mover should be ignored. Otherwise Mover shouldn't be ignored and `isGroupperFirst` should be false (if there is no deeper Groupper in the context).

fix(Mover, Groupper): Properly prioritizing grouppers and movers in the context when they are on the same element.

---

src/MutationEvent.ts
src/Tabster.ts
src/Types.ts
src/Utils.ts
tests/DummyInputManager.test.tsx

Two optimizations regarding dummy inputs:
1. There is no mutation observed in `DummyInputManagerCore` anymore. We're utilizing the main mutation observer to keep the dummy inputs DOM placement consistent. And the DOM placement update is throttled to reduce the amount of reflows.
2. Every `DummyInputManagerCore` doesn't update the dummy input visual position on scroll independently, it is being queued to do the bulk-update in order to reduce the amount of reflows.

feat(DummyInput): Using only main mutation observer to update dummy inputs in DOM and bulk-updating transform offsets

---

src/EventTarget.ts

In Safari 13 (which is supported by Loop), EventTarget exists but is not constructable. This change updates the code to fallback if the class isn't constructable.
A `typeof EventTarget === 'function'` check *might* also work here, but I didn't have a copy of Safari 13 to test with.

Check if EventTarget is constructable

---

src/Groupper.ts
src/Mover.ts
tests/Groupper.test.tsx
tests/Mover.test.tsx
tests/utils/BroTest.ts

This is to give people extra options to fall back to default behaviour (like scrolling the page) or give the application options for handling the key presses.

feat(Mover, Groupper): Ignore handling arrows in Mover and Enter/Esc in Groupper when Ctrl, Alt, Shift or Meta keys are pressed.

---

src/CrossOrigin.ts
tests/CrossOrigin.test.tsx

observedElement.requestFocus() can wait for an element to become accessible within the specified timeout and focus it right after. The cross origin version internally wasn't passing the argument to do so — if an observed element existed on the page but wasn't accessible (like having aria-hidden, for example), requestFocus() was immediately returning with no focused element.

fix(CrossOrigin): Fixing the cross origin version of requestFocus() not waiting for the element to become accessible.

---

src/Utils.ts
tests/DummyInputManager.test.tsx

Dummy inputs are supposed to be first/last elements in the container. When new DOM is appended after the dummy input, Tabster will schedule a position update on the next tick. In the real world it is hardly possible to press Tab between the DOM update and the scheduled dummy input update, but in the test environment it is easily possible. Because the position affects the behaviour like `moveOutWithDefaultAction()`, we enforce its update from the move out functions.

fix(DummyInput): Force dummy input position update when it is needed before the scheduled update.

---

src/Focusable.ts
src/Outline.ts
src/Utils.ts

Working around that document.body.parentElement.parentElement is not null in Firefox in some environments because of some yet unknown reason.

fix: Making sure getComputedStyle() is called for a Node.ELEMENT_NODE only.

---

src/Mover.ts
src/Types.ts
stories/Mover/Mover.ts
tests/Mover.test.tsx

Linear direction can be used in selection components that have grid layout, like emoji picker: 
|  `A1` | `B1`  | `C1`  |
|---|---|---|
| `A2`  | `B2`  | `C2`  |
When user navigates with right arrow key, the order is `A1` -> `B1` -> `C1` -> `A2` and so on.
The user can still use down arrow to move from `A1` to `A2`.
Previously there was just `isGrid` flag handling grid navigation, with a comparison that nullifies the result when X is not as it is needed for table in keydown handler of Mover.ts. These conditions have been extended to account for linear grid.

Grid with linear direction

---

src/Modalizer.ts
src/Tabster.ts
src/Types.ts
tests/Modalizer.test.tsx

By default everything outside of the active Modalizer gets aria-hidden attribute. We are adding option to be able to exclude some particular elements (for example aria-live announcement containers) from receiving aria-hidden.

feat(Modalizer): A createTabster() option to provide alwaysAccessibleSelector selector for the elements to not set aria-hidden on.

---

src/Deloser.ts
tests/Deloser.test.tsx

If there is an input with name "id" in a form, element.id will target that input field instead of the id attribute of the form.
```html
<form id="foo">
<input type="hidden" name="id" value="1" />
</form>
```
Means, if in the current iteration of buildElementSelector, the `element` is the `<form>`-element,
```js
element.id
```
will point to the input.
Therefore using `element.getAttribute("id")` will make sure, that the id-attribute of the current element is used.

Use getAttribute instead of accessing id directly

---

src/Modalizer.ts
src/Tabster.ts
src/Types.ts
tests/Modalizer.test.tsx

Active Modalizer sets `aria-hidden` to everything outside to hide it from screen readers. We already have `alwaysAccessibleSelector` selector to avoid setting `aria-hidden` on some elements that match a specific selector. This is another option to do the same but programmatically.

feat(Modalizer): An accessibleCheck callback for getModalizer() to be able to avoid setting aria-hidden on specific elements.

---

src/Restorer.ts
tests/Restorer.test.tsx

In the cases where the actual restorer is not created yet and the target is focused - it will not be in history. This is because tabster does not exist on the element yet.
Handle this case specifically on creation and add a new target element to history if it is already the active element

fix: Restorer should add target to history on creation if focused

---

src/Restorer.ts

Fixes #305
Not sure if this is the best approach, but it does fix the root issue. Some of the constraints are:
- `document.activeElement` has already been set to `body` by the time the MutationObserver removedNodes mutation is detected
- Non-Chromium browsers fire literally no events when the focused element is removed from the DOM & `activeElement` is set to `body`
- This could in theory be fixed by firing `.blur()` on the `document.activeElement` _before_ it's removed, if we can figure out any way to do so
Here's a reduced demo of the basic issue in Safari & Firefox: https://jsfiddle.net/5pcf9L64/

fix: Restorer should restore focus when element is removed in Safari & Firefox

---

src/Root.ts
src/Tabster.ts
src/Types.ts
tests/Tabster.test.tsx

Adds a new `getParent` prop for `createTabster. This lets users override how to get a parent of a HTMLElement, which is useful for libraries like Fluent UI where the parentElement does not need to follow the DOM order.

feat: getParent prop for createTabster

---

src/Groupper.ts
src/Modalizer.ts
src/Mover.ts
src/Utils.ts

Some memory leaks are hard to identify. When we hold strong references, Tabster might appear as the source of the memory leak in the investigations. So, we're not holding strong references to the observed dummies anymore.

feat(DummyInputObserver): Keeping only weak references in the DummyInputObsrver.

---

src/Mover.ts
tests/Mover.test.tsx

We have a case for Mover to ignore handling keypresses when a focused element has `aria-expanded=true` to work around comoboxes inside Mover. This PR narrows the check to not just `aria-expanded` but also `aria-activedescendant`, as just `aria-expanded` could also be used in different scenarios.

fix(Mover): Fixing how Mover handles elements with aria-expanded.

---

src/Modalizer.ts
src/Restorer.ts
src/Types.ts
src/Utils.ts

Some environments still don't have WeakRef, so we're adjusting to handle those.

fix: Changing usages of WeakRef to internal WeakHTMLElement that has handling of the environments that do not have WeakRef.

---

CredScanSuppressions.json

As part of the 1ESPT compliance work, the new pipeline compliance steps are discovering that there are secrets. Validated that these are false positives of external dependencies.

Add CredScan filter to address false positives

---

src/Mover.ts
tests/MoverGroupper.test.tsx

In case of nested movers, when the inner mover's container is focusable, the current element was memorized on that inner mover, not on the parent mover. Because of that memorizeCurrent behaviour of the parent mover didn't work properly.
When the movers are nested and something in the inner mover receives focus, the parent movers were not populated with the proper current element.

fix(Mover): Fixing the case when focusable mover container was causing memorization of current element on the wrong mover.

---

src/State/FocusedElement.ts
src/Tabster.ts
src/Types.ts
src/Uncontrolled.ts
tests/Uncontrolled.test.tsx

Currently we have `checkUncontrolledTrappingFocus` callback in `createTabster()` to provide the flag that an uncontrolled area is trapping focus. Adding `completely` property to uncontrolled props on DOM element to be able to set this indicator right on the particular DOM elements. Also deprecating `checkUncontrolledTrappingFocus` and adding `checkUncontrolledCompletely` for the sake of consistency and better coexistence.

feat(Uncontrolled): completely prop to indicate that uncontrolled area fully controls Tab.

---

src/Groupper.ts
src/Mover.ts
src/Root.ts
src/State/FocusedElement.ts
src/Types.ts
src/Utils.ts
tests/DummyInputManager.test.tsx
tests/Groupper.test.tsx
tests/Modalizer.test.tsx
tests/Mover.test.tsx

Adding `tabster:movefocus`. Whenever Tabster wants to move focus as the result of a keydown, this event will be triggered. The application can do `event.preventDefault()` to prevent Tabster from what it is going to perform.

feat: Adding tabster:movefocus DOM event which is triggered every time Tabster wants to move focus.

---

src/Groupper.ts
src/Types.ts
tests/Modalizer.test.tsx

When a Modalizer is combined with Groupper and Esc is pressed, we do standard Groupper behaviour of deactivating the Groupper and going to its container. This PR fixes lost focus when the Modalizer is multipart and one part of it is removed on Esc.

fix(Groupper,Modalizer): Fixing async Esc handling when Groupper is combibed with Modalizer.

---

src/Groupper.ts
src/Mover.ts
src/State/FocusedElement.ts
src/Tabster.ts
src/Types.ts
src/Utils.ts
src/index.ts
tests/FocusedElement.test.tsx
tests/Groupper.test.tsx
tests/Modalizer.test.tsx
tests/Mover.test.tsx
tests/Root.test.tsx
tests/index.html
tests/utils/BroTest.ts

Adding `tabster:groupper:movefocus` and `tabster:mover:movefocus` for the application to move focus by triggering them.

Move focus APIs and custom events to move focus.

---

src/Mover.ts
src/Tabster.ts
src/Types.ts
src/Utils.ts
src/index.ts
tests/Mover.test.tsx
tests/index.html
tests/utils/BroTest.ts

It is now possible to dispatch `tabster:mover:memorized-element` custom event to an element inside Mover to forget or alter the memorized element. Comes with `dispatchMoverMemorizedElementEvent()` convenience method.

feat(Mover): Event to forget or alter memorized element in Mover with memorizeCurrent.

---

src/CrossOrigin.ts
src/Deloser.ts
src/Events.ts
src/Types.ts
tests/Deloser.test.tsx

Deloser now dispatches TabsterMoveFocusEvent before restoring the focus. It is possible for application to preventDefault() this event.
Adding strategy prop to Deloser with new `Manual` value. Manual delosers won't restore focus automatically, but they still follow the focus history.
It is possible for the application to dispatch DeloserRestoreFocusEvent to force the Deloser to restore focus.

feat(Deloser): Preventable events to control Deloser, manual focus restoration Deloser strategy.

---

src/Groupper.ts
src/Restorer.ts
src/State/FocusedElement.ts
src/Types.ts
tests/Restorer.test.tsx

Tabster does some focus movements asynchronously. Restorer restores lost focus asynchronously (to give the DOM the opportunity to finish the changes), Groupper handles Esc asynchronously (to give the application ability to handle Esc inside the Groupper).
This PR fixes the conflicts when both Groupper and Restorer want to move focus at the same time.

Fixing races between parts of Tabster that want to focus something asynchronously.

---

src/Deprecated.ts
src/Events.ts
src/index.ts
tests/utils/BroTestEnvironment.ts

Making sure CustomEvent usage doesn't throw undefined reference in Node.js environments.
Adding back custom dispatch event functions from before the events refactoring (done here: https://github.com/microsoft/tabster/pull/358) and marking them as deprecated.

Node.js environment compatibility for CustomEvent usage, exposing old dispatch event functions marked as deprecated.

---

src/Groupper.ts
src/Keys.ts
src/Modalizer.ts
src/Mover.ts
src/State/FocusedElement.ts
tests/Groupper.test.tsx
tests/Modalizer.test.tsx
tests/Restorer.test.tsx

`KeyboardEvent.keyCode` is deprecated and some testing frameworks are dropping support for it. Replacing `keyCode` usages with `key` usages.

Replacing keyCode usages with key.

---

src/Utils.ts
tests/Focusable.test.tsx

Related to #329
There's a bug where fixed elements that are hidden with `display: none`, or nested within another element with `display: none` were still treated as focusable.
This adds an additional check to `isDisplayNone` to catch fixed & hidden elements, as well as tests.

fix: hidden fixed elements do not receive focus

---

src/Types.ts

Adds missing elements to focusable selector (fixes a bug on the Fluent docs site).
It might also be worth considering taking a dependency on https://github.com/KittyGiraudel/focusable-selectors instead of maintaining this internally.

fix: add details > summary, audio, and video to focusable selector

---

src/Modalizer.ts
src/Types.ts
tests/Modalizer.test.tsx

When Modalizer sets aria-hidden for elements outside of active modalizer, it checks if the element is inside the modalizer first. In combination with custom getParent() this allows to avoid setting aria-hidden on elements which are virtually part of the modalizer (like popups rendered to body). However, this is not enough when the virtual children are placed into an extra container. noDirectAriaHidden could be set on the container and instead of setting aria-hidden directly,  Modalizer will go inside the container and set aria-hidden on its children considering the virtual parenthood of each child.

feat(Modalizer): Adding semi-internal noDirectAriaHidden flag to tap into the process of setting aria-hidden.

---

src/Root.ts
tests/Mover.test.tsx

Tabster supports custom getParent() function which allows virtual parentship. Here we make Mover to handle only real children. This fixes #374.

fix(Mover): Excluding possible out of DOM order virtual children from Mover.

---

src/Mover.ts
tests/Mover.test.tsx

Making sure Mover doesn't try to focus memorized element that is removed from DOM, but hasn't been garbage collected yet.

fix(Mover): Checking that memorized element is still focusable.

---

docs/package-lock.json
package-lock.json
package.json

- bumps vulnerable `loader-utils` and `shell-quote` deps to versions where fix was employed. Fix for `loader-utils` is version `2.0.3` and up while for `shell-quote` it's version `1.7.3` and up.
- had to use `override` `loader-utils` for root `package.json` because the repo relies on storybook 6 which brings in webpack 4 and that uses version`1.x` of `loader-utils`. Upgrading from storybook 6 is a big undertaking so skipped that step in this case.
- bumps made in `docs/` `package.json` were simply done with `npm update loader-utils` and `npm update shell-quote` respectively

chore: bump loader-utils and shell-quote deps 

---

azure-pipelines.yml

Adds `skipPublish` pipeline variable to release pipeline to enable running without triggering a new publish to npm. Default value is `false` to maintain previous behavior

ci: add skipPublish variable to release pipeline

---

azure-pipelines.yml

Release pipeline is hanging on `Npm@1` task
Now using `npm install` command directly which will hopefully fix the issue

ci(release): invoke npm install directly instead of using azure task

---

azure-pipelines.yml
docs/package-lock.json
docs/package.json

- `npm install` was hanging in CI and that's caused by puppeteer versions < 22 . Workaround suggested by [this comment](https://github.com/puppeteer/puppeteer/issues/12833#issuecomment-2255014295) and it does work in installing packages in CI successfully ([see test pipeline run](https://dev.azure.com/uifabric/UI%20Fabric/_build/results?buildId=358181&view=logs&j=7494ae37-3ecd-50c6-9ffe-c77a2768c545&t=e3b22a90-6f85-5d9d-3b61-aa02f6a40c65))
- adds overrides for `loader-utils` and `shell-quote` deps to `docs` package as those were still being flagged by component governance
Related to this issue: https://github.com/npm/cli/issues/4028

ci(release): fix npm install hang and address critical security deps

---

src/Restorer.ts
src/Types.ts
tests/Restorer.test.tsx

Introduces `id` attribute to `restorer`.
Providing an `id` will link a `source` with a `target` ensuring that focus restoration will only happen if the `id` is compatible between the `source` and the `target` element
Fixes https://github.com/microsoft/tabster/issues/413

feature(restorer): link source and target by id

---

src/Modalizer.ts
tests/Modalizer.test.tsx

For a trapped modal with no focusable descendants, tabster should prevent focus from leaving it.

fix(modalizer): stop focus from leaving trapped modal w/ no focusable descendants

---

src/State/FocusedElement.ts
src/State/ObservedElement.ts
src/Types.ts

```ts
.requestFocus("name", 1000);
```
`.requestFocus()` gets `options` as a param and exposes `preventScroll` option:
```ts
.requestFocus("name", 1000);
.requestFocus("name", 1000, { preventScroll: true });
```
This aligns `.requestFocus()` with [`.focus()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus).

feat(ObservedElementAPI): add `options` to `requestFocus()`

---

src/Consts.ts
src/State/ObservedElement.ts
src/Types.ts
tests/ObservedElement.test.tsx

When requestFocus() request resolves with `true` or `false`, in case of `false` it was not possible to tell the difference between timed out request or canceled request (older requests get canceled when a new request is made or when a user has moved focus). Adding status to be able to tell one from another.

feat(ObservedElement): Adding observed element request status.

---

src/Modalizer.ts
src/Types.ts
tests/Modalizer.test.tsx

In some cases we might want to activate Modalizer without moving focus (for example there are no focusable elements yet, but we already want to activate focus trap and deactivate the rest of the app). This PR adds new method `activate()` to the Modalizer API.

feat(Modalizer): A method to activate modalizer without moving focus.

---

src/State/ObservedElement.ts

Tests are failing:
See for context https://github.com/microsoft/fluentui/pull/34291.
Tests are passing:

fix: unhandled promise rejection in ObservedElementAPI
