- README.md
- core/package.json
- examples/.gitignore
- examples/.npmrc
- examples/.storybook/main.js
- examples/.storybook/preview-head.html
- examples/.storybook/preview.js
- examples/README.md
- examples/package.json
- examples/src/Groupper.stories.tsx
- examples/src/Modalizer.stories.tsx
- examples/src/Mover.stories.tsx
- examples/src/components/Item.tsx
- examples/src/components/Modal.tsx
- examples/tsconfig.json
- lerna.json
- package.json
This PR introduces a new `examples` package that can live reload changes
made to the `core` package.
The intention is to improve contributor experience and have a simple
`yarn start` experience to experiment, and also serves as a living
documentation.
> Introduce storybook for repo

- examples/src/KeyboardNavigationState.stories.tsx
Adds a simple navigation to see if an element was focused with keyboard
navigation or mouse
> Add keyboard navigation state example

- lint/package.json
- package.json
Curently repo build is relatively fast, we can leverage pre-push hook to
build code as cheap man's automation
> Add pre-push hook to build repo

- .github/workflows/ci.yml
- examples/package.json
- fix commands in GH action to have "run"
- adds cross-env to make scripts working on Windows
> chore: fix commands in GH action & fix run on Windows

- .github/workflows/github-pages.yml
This PR adds a GitHub workflow to deploy Storybook to GitHub pages.
> chore: add Storybook deployment to Github pages

- core/src/Root.ts
- core/src/State/FocusedElement.ts
- keyborg/src/FocusEvent.ts
- keyborg/src/Keyborg.ts
- keyborg/src/WeakRefInstance.ts
- keyborg/src/index.ts
Adds docstrings and renames some things for readability
Dedupes multipe `WeakRef` classes by creating a weak ref generic wrapper
> chore(keyborg): Cleaup and dedupe

- demo/package.json
- demo/webpack.config.js
Fixes the error in s-panferov/awesome-typescript-loader#372
> fix(demo): Replace awesome-typescript-loader with ts-loader

- core/jest.config.json
- core/src/Modalizer.ts
- core/src/__tests__/Deloser.test.tsx
- core/src/__tests__/Groupper.test.tsx
- core/src/__tests__/Modalizer.test.tsx
- core/src/__tests__/Mover.test.tsx
- core/testing/BroTest.ts
- test-container/webpack.config.js
Adds tests for:
* Groupper
* Modalizer
* Mover
At least for what I currently know should be correct behaviour
> chore(Tests): Add initial tests for tabster

- examples/tsconfig.json
1. Removes external paths from tsconfig, (instead of `../../core/src/index.ts` uses `tabster/src/index.ts`)
> Upgrades storybook tsconfig

- .github/workflows/github-pages.yml
updated by the github-pages pipeline was not.
Update `github-pages.yml` to use node 14
> fix(ci): use Node 14

- .gitignore
- core/.storybook/main.js
- core/.storybook/preview.js
- core/package.json
- core/src/stories/Groupper/Groupper.stories.ts
- core/src/stories/Groupper/Groupper.ts
- core/src/stories/Groupper/groupper.css
- core/src/stories/Modalizer/ModalDialog.ts
- core/src/stories/Modalizer/Modalizer.stories.ts
- core/src/stories/Modalizer/modalizer.css
- core/src/stories/Mover/Mover.stories.ts
- core/src/stories/Mover/Mover.ts
- core/src/stories/Mover/mover.css
Setup a storybook in `core` for the removal of `examples` and
`demo` packages in a follow up PR.
The stories include
* Mover
* Modalizer
* Groupper
> chore(storybook): Adds @storybook/html to `core`

- .github/workflows/github-pages.yml
- package.json
Adds an extra step to the github pages CI after changes from #101
> fix: docs deploy

- .github/workflows/ci.yml
- azure-pipelines.yml
- package-lock.json
Adds a check in CI to make sure that after the run there are no unstaged files.
Also fixes the package-lock.json that is currently not correct in master
> Add CI step to check for unstaged files

- src/Modalizer.ts
> feat: adds aria-labelledby as possible required attribute for Modalizer

- src/Root.ts
- src/State/FocusedElement.ts
- src/Utils.ts
- tests/DummyInputManager.test.tsx
- tests/Focusable.test.tsx
- tests/Groupper.test.tsx
- tests/Root.test.tsx
- tests/Uncontrolled.test.tsx
- tests/utils/test-utils.ts
Fixing uncontrolled corner cases.
> fix(Uncontrolled): Handling Uncontrolled areas before and after Mover/Groupper with another Uncontrolled.

- .gitignore
- src/Mover.ts
- stories/Mover/Mover.stories.ts
- stories/Mover/Mover.ts
- tests/Mover.test.tsx
The algorithm to calculate vertically next element in grid was insufficient. Replacing it with a better working one and adding tests.
> fix(Mover): Fixing Mover grid behaviour and adding tests for it.

- docs/package-lock.json
> Revert "chore(deps): bump @sideway/formula from 3.0.0 to 3.0.1 in /docs"

- package-lock.json
> Revert "chore(deps): bump @sideway/formula from 3.0.0 to 3.0.1"

- azure-pipelines.yml
This is required for compliance.
> Enable 1ESPT pipelines

- src/MutationEvent.ts
- tests/Internal.test.tsx
When a node is removed and the attribute of the removed node is changed in the same tick as the removal, MutationObserver gets an event with two mutation records: for both the node removal and the attribute change. That order was causing recreation of untracked Tabster instances.
> fix: Fixing memory leak in a specific DOM change scenario.
